import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import GlobalStylesProvider from "./providers/GlobalStylesProvider";
import ContextProvider from "./providers/ContextProvider";

const inter = Poppins({subsets: ["latin"], weight: "400"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/5df6411027.js"
          crossOrigin="anonymous"></script>
      </head>
      <body className={inter.className}>
        <ContextProvider>
          <GlobalStylesProvider>
            <Sidebar />
            {children}
          </GlobalStylesProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
